n1 = float(input("Digite a 1 nota: "))
n2 = float(input("Digite a 2 nota: "))
n3 = float(input("Digite a 3 nota: "))
n4 = float(input("Digite a 4 nota: "))
media = (n1*1 + n2*2 + n3*3 + n4*4) / (1+2+3+4)
print("Media ponderada: ", round(media, 2))