print("Adicao: ", 5 + 3)
print()
print("Subtracao: ", 10 - 2)
print()
print("Multiplicacao: ", 4*2)
print()
print("Divisao: ", 16/2)
print()
print("Resto: ", 8)
print()
print("Potenciacao: ", 2**3)
print()