var = input("Informe seu nome: ")
print("")
int = input("Informe a sua idade:")
print("")
real = input("Informe a sua Altura: ")
print("")
print("VOCÊ DIGITOU")
print("Nome:",var)
print("Idade:",int)
print("Altura:",real)