n1 = float(input("Digite a nota 1:"))
n2 = float(input("Digite a nota 2:"))
n3 = float(input("Digite a nota 3:"))
n4 = float(input("Digite a nota 4:"))
media = ((n1*1)+(n2*2)+(n3*3)+(n4*4))/(1+2+3+4)
print(round(media, 2))
