Nome = input ('Digite seu nome: ')
print()
Idade = input ('digite sua idade: ')
print()
Altura = input ('Digite sua altura: ')
print()

print ('Nome:', Nome)
print ('Idade:', Idade)
print ('Altura:', Altura)